### ISSUE TITLE
插件导致「百度网盘 」网页改版后主题 CSS 样式错误

### ISSUE THREAD

**Issue by onestark** [acgotaku/BaiduExporter#340]
网盘网页改版后，新增了可选主题，但是插件的 CSS 样式强制使所有主题的顶栏和侧栏文字颜色为灰色 `#666`。建议插件注释掉以下 CSS 部分：

```css
a {
    color: #666 !important;
    text-decoration: none !important;
}
```

主题正常样式：

![normal](https://cloud.githubusercontent.com/assets/3352695/19636983/287022dc-99ff-11e6-8398-70d46a85c7b2.png)

启用插件后主题样式：

![bug](https://cloud.githubusercontent.com/assets/3352695/19637008/47051414-99ff-11e6-9e05-760161682c3e.png)
